### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [skycloud1030/array-includes-any#2]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by skycloud1030** [comment]
@geopic  
I like your feedback, welcome to send us a Pull Request for it. Please send your Pull Request to proper branch

**Comment by geopic** [comment]
Good stuff, I'll start now.
